//! Arq is a library to simplify interactions with files backed up by
//! [Arqbackup](https://www.arqbackup.com/).
//!
//! Currently it supports only files generated by Arq (the program) versions 4.5 and above.
//!
//! In its present state, this library allows reading files but never writing, so it's not
//! possible to build a full replacement of Arq (the program) with this library.
//!
//! NOTE: A lot of the documentation, especially the one describing the data formats,
//! comes from [https://arqbackup.com](https://www.arqbackup.com/arq_data_format.txt). All
//! credit should go to those folks.
//!
//! ## Installation
//!
//! Add this to your `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! arq = "0.1"
//! ```
//!
//! **For a more complex example, please check a command line tool (evu) built using this
//! library at [https://github.com/nlopes/evu](https://github.com/nlopes/evu).**
extern crate aes;
extern crate byteorder;
extern crate chrono;
#[cfg_attr(test, macro_use)]
extern crate hex_literal;
extern crate hmac;
extern crate plist;
extern crate ring;
extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;
extern crate sha1;
extern crate sha2;

pub mod arq7;
pub mod blob_location;
pub mod compression;
pub mod computer;
pub mod error;
pub mod folder;
pub mod node;
pub mod object_encryption;
pub mod packset;
pub mod tree;
pub mod type_utils;

mod blob;
mod date;
mod lz4;
mod utils;
