name: CI

on:
  pull_request:
  push:
    branches:
      - latest

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta]
        experimental: [false]
        include:
          - rust: nightly
            os: ubuntu-latest
            experimental: true

    steps:
    - uses: actions/checkout@master

    - name: check
      run: cargo check --tests --all-targets

    - name: tests
      run: cargo test --verbose
      env:
        RUST_BACKTRACE: short

  check_fmt_and_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: clippy
      run: cargo clippy --tests --all-targets

    - name: fmt
      run: cargo fmt --all -- --check

    - name: docs
      run: cargo doc --no-deps
